In [70]:
import pandas as pd
import sys
import glob
import os.path

In [71]:
folder_name = "./data/"

data_path = os.path.join(folder_name,'*xlsx')

files = glob.glob(data_path)

In [72]:
files

['./data/v2017.xlsx',
 './data/v2012.xlsx',
 './data/v2013.xlsx',
 './data/v2015.xlsx',
 './data/v2018.xlsx',
 './data/v2014.xlsx',
 './data/v2016.xlsx']

In [73]:
years = []
for file in files:
    df = pd.read_excel(file, sheet_name = None)
    year = file.replace('./data/v', '')
    year = year.replace('.xlsx', '')
    years.append([df, year])
    df['Hoja1'].to_pickle(year)

In [75]:
def extract_product_tables(df): 
    cols = ['PRODUCTO', 'CARGA', 'EXISTENCIA', 'DEVOLUCION', 'VENTA TOTAL', 'PRECIO * PRODUC', '$', 'VENTA EN LT', 'RUTA', 'DIA', 'SEMANA']
    productos = pd.DataFrame(columns= cols)
    test_copy = df
    for i in range(int(df.shape[0])):
        for j in range(int(df.shape[1])):
            if type(df.iloc[i, j]) == unicode and ('RUTA:' in df.iloc[i, j] or 'IVAN' in df.iloc[i, j]):
                ruta = ''
                dia = ''
                semana = ''
                ruta = df.iloc[i, j]
                if type(df.iloc[i - 1,j]) == unicode:
                    dia = df.iloc[i - 1, j]
                if type(df.iloc[i - 2,j]) == unicode and 'SEMANA' in df.iloc[i - 2,j]:
                    semana = df.iloc[i - 2, j]
                new_entry = test_copy.iloc[i + 2:i + 10, j:j + 12].T
                new_entry['RUTA'] = ruta
                new_entry['DIA'] = dia
                new_entry['SEMANA'] = semana
                new_entry.columns = cols
                if ruta != '' and not 'QUESO' in ruta:
                    productos = productos.append(new_entry, ignore_index=True)
    return productos

In [ ]:
cols = ['PRODUCTO', 'CARGA', 'EXISTENCIA', 'DEVOLUCION', 'VENTA TOTAL', 'PRECIO * PRODUC', '$', 'VENTA EN LT', 'RUTA', 'DIA', 'SEMANA', 'ANIO']
productos = pd.DataFrame(columns= cols)
for year in years:
    year_raw = year[0]['Hoja1']
    year_name = year[1]
    year_products = extract_product_tables(year_raw)
    year_products['ANIO'] = year_name
    productos = productos.append(year_products, ignore_index=True)

In [26]:
productos.shape

(82200, 12)

In [27]:
productos.to_pickle('productos')

In [69]:
test_prod = pd.read_pickle('productos')
test_prod['RUTA']
rutas = []
for ruta in test_prod['RUTA']:
    if not ruta in rutas:
        rutas.append(ruta)
rutas

[u'RUTA: FERMIN',
 u'RUTA: JUGUERAS',
 u'RUTA: SAN MARCOS',
 u'RUTA:MARTIN',
 u'RUTA: MARTIN',
 u'RUTA: ERICK',
 u'RUTA: JESUS',
 u'RUTA: TRADICION']

In [ ]:
# LIMPIAA!

In [33]:
# Eliminamos NaNs de la columna productos:
productos = productos.dropna()

<bound method Series.unique of 0         PRODUCTO8
1         PRODUCTO3
2         PRODUCTO7
3         PRODUCTO2
4         PRODUCTO1
5         PRODUCTO5
11         PRODUCTO
23         PRODUCTO
47         PRODUCTO
59         PRODUCTO
79        PRODUCTO5
80        PRODUCTO1
83        PRODUCTO8
84        PRODUCTO8
85        PRODUCTO3
86        PRODUCTO7
87        PRODUCTO2
88        PRODUCTO1
89        PRODUCTO5
90        PRODUCTO9
95         PRODUCTO
107        PRODUCTO
120       PRODUCTO8
121       PRODUCTO3
122       PRODUCTO7
123       PRODUCTO2
124       PRODUCTO1
125       PRODUCTO5
126       PRODUCTO9
131        PRODUCTO
            ...
81743      PRODUCTO
81767      PRODUCTO
81787     PRODUCTO5
81788     PRODUCTO1
81791     PRODUCTO8
81803      PRODUCTO
81827      PRODUCTO
81840    PRODUCTO10
81851      PRODUCTO
81875      PRODUCTO
81899      PRODUCTO
81923      PRODUCTO
81943     PRODUCTO5
81944     PRODUCTO1
81947     PRODUCTO8
81959      PRODUCTO
81983      PRODUCTO
81996    PRODUCTO10
82007      PRODUCTO
82031      PRODUCTO
82055      PRODUCTO
82079      PRODUCTO
82099     PRODUCTO5
82100     PRODUCTO1
82103     PRODUCTO8
82115      PRODUCTO
82139      PRODUCTO
82152    PRODUCTO10
82163      PRODUCTO
82187      PRODUCTO
Name: PRODUCTO, Length: 18615, dtype: object>

In [35]:
# Eliminamos todas las observaciones que sean en realidad los nombres de las columnas
productos = productos.loc[productos['CARGA'] != 'CARGA']

In [58]:
copy_todo = productos
rutas = []
for ruta in copy_todo['RUTA']:
    while ruta[0] == ' ':
        ruta = ruta[1:]
    while '  ' in ruta:
        ruta = ruta.replace('  ', ' ')
    ruta = ruta.replace(': ', ':')
    if not ruta in rutas:
        rutas.append(ruta)
rutas

[u'RUTA:FERMIN',
 u'RUTA:SAN MARCOS',
 u'RUTA:JUGUERAS',
 u'RUTA:MARTIN',
 u'RUTA:ERICK',
 u'RUTA:JESUS']

In [63]:
productos.loc[' RUTA:TRADICION' == productos['RUTA']]

Empty DataFrame
Columns: [PRODUCTO, CARGA, EXISTENCIA, DEVOLUCION, VENTA TOTAL, PRECIO * PRODUC, $, VENTA EN LT, RUTA, DIA, SEMANA, ANIO]
Index: []

In [9]:
productos.loc[productos['CARGA'] == 'CARGA']

,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA,DIA,SEMANA
11,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,,SEMANA DEL 31 AL 5 ENERO 2017
23,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,SABADO,
47,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,,
59,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA:LUNES,
95,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA MARTES,
107,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA MERTES,
131,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,MIERCOLES,
143,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA MIERCOLES,
167,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,jueves,
179,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA JUEVES,
203,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA VIERNES,
215,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,,
239,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,,SEMANA DEL 7 AL 13 ENERO 2017
251,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,SABADO,
275,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,,
287,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA:LUNES,
323,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA MARTES,
335,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA MERTES,
359,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,MIERCOLES,
371,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA MIERCOLES,
395,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,jueves,
407,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA JUEVES,
431,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA VIERNES,
443,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,,
467,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,,SEMANA DEL 7 AL 13 ENERO 2017
479,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,SABADO,
503,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA:LUNES,
539,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA MARTES,
551,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA MERTES,
575,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,MIERCOLES,
...,...,...,...,...,...,...,...,...,...,...,...
13811,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA MERTES,
13835,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA: MIERCOLES,
13847,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: MARTIN,DIA: MIERCOLES,
13859,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA MIERCOLES,
13883,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA: JUEVES,
13895,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: MARTIN,DIA: JUEVES,
13907,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA JUEVES,
13931,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA: VIERNES,
13943,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: MARTIN,DIA: VIERNES,
13955,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: ERICK,DIA: LUNES,
13967,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,,
13991,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA: SABADO,
14003,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA:MARTIN,DIA: SABADO,
14015,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,SABADO,
14039,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA: LUNES,
14051,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: MARTIN,DIA: LUNES,
14063,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA:LUNES,
14099,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA: MARTES,
14111,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: MARTIN,DIA: MARTES,
14123,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA MERTES,
14147,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA: MIERCOLES,
14159,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: MARTIN,DIA: MIERCOLES,
14171,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA MIERCOLES,
14195,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA: JUEVES,
14207,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: MARTIN,DIA: JUEVES,
14219,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,DIA JUEVES,
14243,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: FERMIN,DIA: VIERNES,
14255,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: MARTIN,DIA: VIERNES,
14267,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: ERICK,DIA: LUNES,
14279,PRODUCTO,CARGA,EXISTENCIA,DEVOLUCION,VENTA TOTAL,PRECIO * PRODUC,$,VENTA EN LT,RUTA: JUGUERAS,,